from fastapi.openapi.utils import get_openapi


def openapi_without_422_errors():
    """
    Hide validation errors generated by FastAPI (status code 422) from the docs
    since we use custom and formatted errors instead (status code 400)
    """
    from main import app

    if app.openapi_schema:
        openapi_schema = app.openapi_schema
    else:
        openapi_schema = get_openapi(
            title=app.title, version=app.version, routes=app.routes, description=app.description
        )

    for method in openapi_schema["paths"]:
        try:
            del openapi_schema["paths"][method]["post"]["responses"]["422"]
        except KeyError:
            pass

    app.openapi_schema = openapi_schema
    return app.openapi_schema
